apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chatdev.fullname" . }}-config
  labels:
    {{- include "chatdev.labels" . | nindent 4 }}
data:
  BASE_URL: {{ .Values.config.baseUrl | quote }}
